export const PORTUGUESE_WORDS = [
  "ABACAXI", "ACIDENTE", "AGENDA", "ALMA", "AMOR", "ANCORA", "ANIMAL", "ARCO",
  "ARENA", "ATOR", "BANCO", "BARCO", "BOLA", "BOMBA", "BRANCO", "BURACO",
  "CABELO", "CAMPO", "CANETA", "CARRO", "CASA", "CAVALO", "CENTRO", "CHAVE",
  "CIRCO", "COBRA", "COELHO", "COROA", "DADOS", "DENTE", "DISCO", "DRAGÃO",
  "DUENDE", "ECLIPSE", "ESCOLA", "ESPADA", "ESTRADA", "ESTRELA", "FADA",
  "FERRO", "FOGO", "FONTE", "GATO", "GELO", "GIGANTE", "GLOBO", "GRAMA",
  "HOTEL", "ILHA", "ÍNDIO", "JANELA", "JARDIM", "JÓIA", "LEÃO", "LIVRO",
  "LUA", "MÁGICO", "MAPA", "MARTELO", "MÉDICO", "MESA", "MONTANHA", "MURO",
  "NAVIO", "NEVE", "NOBRE", "NUVEM", "OCEANO", "OLHO", "ONDA", "OURO",
  "PALCO", "PEDRA", "PIANO", "PIRATA", "PLANTA", "PONTE", "PRAIA", "PRÍNCIPE",
  "RAIO", "RATO", "RELÓGIO", "ROBÔ", "ROSA", "SAMBA", "SETA", "SOL",
  "SOMBRA", "TAMBOR", "TEMPO", "TIGRE", "TORRE", "TREM", "TROVÃO", "TUBARÃO",
  "URSO", "VAMPIRO", "VELA", "VENTO", "VERDE", "VULCÃO", "XADREZ", "ZEBRA",
  "AÇÚCAR", "AGULHA", "ALGODÃO", "ANEL", "ANZOL", "ARANHA", "ÁRVORE",
  "ASTRONAUTA", "BALEIA", "BANANA", "BATERIA", "BICICLETA", "BIGODE",
  "BÚSSOLA", "CABEÇA", "CAFÉ", "CANHÃO", "CAPITÃO", "CHAPÉU", "CHOCOLATE",
  "CIDADE", "CINEMA", "COMETA", "CORTINA", "CRIANÇA", "DIAMANTE", "DINOSSAURO",
  "ELEFANTE", "ENGENHO", "ESPELHO", "FÁBRICA", "FANTASMA", "FLORESTA",
  "FOGUETE", "GALÁXIA", "GUERREIRO", "GUITARRA", "HELICÓPTERO", "INVASÃO",
  "LABIRINTO", "LÂMPADA", "MÁSCARA", "MICROSCÓPIO", "MOLDURA", "NASCENTE",
  "PALHAÇO", "PARAQUEDAS", "PASSARINHO", "PENGUIM", "PIRÂMIDE", "POLVO",
  "PRESENTE", "PROFESSOR", "QUADRO", "RAINHA", "RECEITA", "REDE", "SAFIRA",
  "SATÉLITE", "SELVA", "SEREIA", "TAPETE", "TELESCÓPIO", "TESOURO", "TORNADO",
  "UNIVERSO", "VENENO", "VIOLINO", "VULTO", "ZUMBI",
]

export function getRandomWords(count: number): string[] {
  const shuffled = [...PORTUGUESE_WORDS].sort(() => Math.random() - 0.5)
  return shuffled.slice(0, count)
}
